#!/usr/bin/env bash
set -euo pipefail

# One-click launcher for a dev Electron instance isolated from official app.
# Uses a separate config dir so .server.lock / workspaces / settings won't conflict.

CRAFT_DEBUG="${CRAFT_DEBUG:-0}"
CRAFT_DEBUG_TITLE="${CRAFT_DEBUG_TITLE:-0}"
CRAFT_DEBUG_TOOL_TITLES="${CRAFT_DEBUG_TOOL_TITLES:-0}"
CRAFT_DEBUG_STREAMING_STEPS="${CRAFT_DEBUG_STREAMING_STEPS:-0}"
CRAFT_DEBUG_SUBMIT_PLAN="${CRAFT_DEBUG_SUBMIT_PLAN:-0}"
CRAFT_DEBUG_TOOL_ARGS="${CRAFT_DEBUG_TOOL_ARGS:-0}"
CRAFT_DEBUG_COMPACTION="${CRAFT_DEBUG_COMPACTION:-0}"
CRAFT_DEBUG_COMPACTION_DELAY_MS="${CRAFT_DEBUG_COMPACTION_DELAY_MS:-}"
CRAFT_DEBUG_FORCE_COMPACT_EVERY_TURNS="${CRAFT_DEBUG_FORCE_COMPACT_EVERY_TURNS:-}"
CRAFT_DEBUG_COMPACTION_CONTEXT_WINDOW="${CRAFT_DEBUG_COMPACTION_CONTEXT_WINDOW:-}"
CRAFT_DEBUG_COMPACTION_THRESHOLD="${CRAFT_DEBUG_COMPACTION_THRESHOLD:-}"
CRAFT_DEBUG_COMPACTION_SUMMARY_IO="${CRAFT_DEBUG_COMPACTION_SUMMARY_IO:-0}"
CRAFT_DEBUG_STARTUP_PATHS="${CRAFT_DEBUG_STARTUP_PATHS:-0}"
CRAFT_DEBUG_FETCH_MODELS="${CRAFT_DEBUG_FETCH_MODELS:-0}"
CRAFT_DEBUG_CONTEXT_WINDOW="${CRAFT_DEBUG_CONTEXT_WINDOW:-0}"
CRAFT_DEBUG_DEEPSEEK_CACHE="${CRAFT_DEBUG_DEEPSEEK_CACHE:-0}"
CRAFT_DEBUG_PROVIDER_RAW_RESPONSE="${CRAFT_DEBUG_PROVIDER_RAW_RESPONSE:-0}"

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Defaults (can override via env before running this script)
CRAFT_CONFIG_DIR="${CRAFT_CONFIG_DIR:-$HOME/.crystal-agent-dev}"
CRAFT_VITE_PORT="${CRAFT_VITE_PORT:-6173}"
CRAFT_APP_VARIANT_PATH="${CRAFT_APP_VARIANT_PATH:-$ROOT_DIR/apps/electron/resources/app-variant.dev.json}"
CRAFT_ELECTRON_USER_DATA_DIR="${CRAFT_ELECTRON_USER_DATA_DIR:-$CRAFT_CONFIG_DIR/electron}"
CRAFT_LOGS_DIR="${CRAFT_LOGS_DIR:-$CRAFT_ELECTRON_USER_DATA_DIR/logs}"

export CRAFT_CONFIG_DIR
export CRAFT_VITE_PORT
export CRAFT_APP_VARIANT_PATH
export CRAFT_ELECTRON_USER_DATA_DIR
export CRAFT_LOGS_DIR
export CRAFT_DEBUG
export CRAFT_DEBUG_TITLE
export CRAFT_DEBUG_TOOL_TITLES
export CRAFT_DEBUG_STREAMING_STEPS
export CRAFT_DEBUG_SUBMIT_PLAN
export CRAFT_DEBUG_TOOL_ARGS
export CRAFT_DEBUG_COMPACTION
export CRAFT_DEBUG_COMPACTION_SUMMARY_IO
export CRAFT_DEBUG_STARTUP_PATHS
export CRAFT_DEBUG_FETCH_MODELS
export CRAFT_DEBUG_CONTEXT_WINDOW
export CRAFT_DEBUG_DEEPSEEK_CACHE
export CRAFT_DEBUG_PROVIDER_RAW_RESPONSE

if [[ -n "$CRAFT_DEBUG_COMPACTION_DELAY_MS" ]]; then
  export CRAFT_DEBUG_COMPACTION_DELAY_MS
fi
if [[ -n "$CRAFT_DEBUG_FORCE_COMPACT_EVERY_TURNS" ]]; then
  export CRAFT_DEBUG_FORCE_COMPACT_EVERY_TURNS
fi
if [[ -n "$CRAFT_DEBUG_COMPACTION_CONTEXT_WINDOW" ]]; then
  export CRAFT_DEBUG_COMPACTION_CONTEXT_WINDOW
fi
if [[ -n "$CRAFT_DEBUG_COMPACTION_THRESHOLD" ]]; then
  export CRAFT_DEBUG_COMPACTION_THRESHOLD
fi

mkdir -p "$CRAFT_CONFIG_DIR" "$CRAFT_ELECTRON_USER_DATA_DIR" "$CRAFT_LOGS_DIR"

echo "[dev-instance] ROOT_DIR=$ROOT_DIR"
echo "[dev-instance] CRAFT_CONFIG_DIR=$CRAFT_CONFIG_DIR"
echo "[dev-instance] CRAFT_VITE_PORT=$CRAFT_VITE_PORT"
echo "[dev-instance] CRAFT_APP_VARIANT_PATH=$CRAFT_APP_VARIANT_PATH"
echo "[dev-instance] CRAFT_ELECTRON_USER_DATA_DIR=$CRAFT_ELECTRON_USER_DATA_DIR"
echo "[dev-instance] CRAFT_LOGS_DIR=$CRAFT_LOGS_DIR"
echo "[dev-instance] MAIN_LOG=$CRAFT_LOGS_DIR/main.log"
echo "[dev-instance] RENDERER_DEBUG_LOG=$CRAFT_LOGS_DIR/renderer-debug.log"
echo "[dev-instance] CRAFT_DEBUG=$CRAFT_DEBUG"
echo "[dev-instance] CRAFT_DEBUG_TITLE=$CRAFT_DEBUG_TITLE"
echo "[dev-instance] CRAFT_DEBUG_TOOL_TITLES=$CRAFT_DEBUG_TOOL_TITLES"
echo "[dev-instance] CRAFT_DEBUG_STREAMING_STEPS=$CRAFT_DEBUG_STREAMING_STEPS"
echo "[dev-instance] CRAFT_DEBUG_SUBMIT_PLAN=$CRAFT_DEBUG_SUBMIT_PLAN"
echo "[dev-instance] CRAFT_DEBUG_TOOL_ARGS=$CRAFT_DEBUG_TOOL_ARGS"
echo "[dev-instance] CRAFT_DEBUG_COMPACTION=$CRAFT_DEBUG_COMPACTION"
echo "[dev-instance] CRAFT_DEBUG_COMPACTION_DELAY_MS=${CRAFT_DEBUG_COMPACTION_DELAY_MS:-unset}"
echo "[dev-instance] CRAFT_DEBUG_FORCE_COMPACT_EVERY_TURNS=${CRAFT_DEBUG_FORCE_COMPACT_EVERY_TURNS:-unset}"
echo "[dev-instance] CRAFT_DEBUG_COMPACTION_CONTEXT_WINDOW=${CRAFT_DEBUG_COMPACTION_CONTEXT_WINDOW:-unset}"
echo "[dev-instance] CRAFT_DEBUG_COMPACTION_THRESHOLD=${CRAFT_DEBUG_COMPACTION_THRESHOLD:-unset}"
echo "[dev-instance] CRAFT_DEBUG_COMPACTION_SUMMARY_IO=$CRAFT_DEBUG_COMPACTION_SUMMARY_IO"
echo "[dev-instance] CRAFT_DEBUG_STARTUP_PATHS=$CRAFT_DEBUG_STARTUP_PATHS"
echo "[dev-instance] CRAFT_DEBUG_FETCH_MODELS=$CRAFT_DEBUG_FETCH_MODELS"
echo "[dev-instance] CRAFT_DEBUG_CONTEXT_WINDOW=$CRAFT_DEBUG_CONTEXT_WINDOW"
echo "[dev-instance] CRAFT_DEBUG_DEEPSEEK_CACHE=$CRAFT_DEBUG_DEEPSEEK_CACHE"
echo "[dev-instance] CRAFT_DEBUG_PROVIDER_RAW_RESPONSE=$CRAFT_DEBUG_PROVIDER_RAW_RESPONSE"
echo "[dev-instance] 推荐：tool-validation 排查可用 CRAFT_DEBUG=1 CRAFT_DEBUG_TOOL_ARGS=1"
echo "[dev-instance] 推荐：自动压缩排查可用 CRAFT_DEBUG=1 CRAFT_DEBUG_COMPACTION=1 CRAFT_DEBUG_COMPACTION_SUMMARY_IO=1"
echo "[dev-instance] 推荐：模型获取排查可用 CRAFT_DEBUG_FETCH_MODELS=1，并从 $CRAFT_LOGS_DIR/main.log 提取 [fetch-models] 日志"
echo "[dev-instance] 推荐：contextWindow 来源排查可用 CRAFT_DEBUG_CONTEXT_WINDOW=1，并从 $CRAFT_LOGS_DIR/main.log 提取 [context-window] 日志"
echo "[dev-instance] 推荐：DeepSeek 缓存排查可用 CRAFT_DEBUG_DEEPSEEK_CACHE=1，并从 $CRAFT_LOGS_DIR/main.log 提取 [deepseek-cache] 日志"
echo "[dev-instance] 推荐：任意 provider 原始响应排查可用 CRAFT_DEBUG_PROVIDER_RAW_RESPONSE=1，并从 $CRAFT_LOGS_DIR/main.log 提取 [provider-raw-response] 日志"

cd "$ROOT_DIR"
exec bun run electron:dev
